import os
from shutil import rmtree


def generate_project():
	print("-- Current working directory: ", os.getcwd())
	if (os.getcwd().endswith("scripts")) or os.getcwd().endswith("scripts/"):
		os.chdir("..")
		print("-- Changed working directory to the parent directory")

	print("-- Checking if a 'build' directory already exists...")
	if os.path.isdir("build"):
		if os.path.exists("build/generate_project.py.output"):
			print("-- Regenerating CMake project\n")
			if (os.system("cd build && cmake ..") == 0):
				print("\n-- CMake regenerated project files successfully")
				return 0
			else:
				print("-- FATAL: CMake failed to regenerate project files")
				return 1
		print("-- Warning: 'build' already exists...")
		str = input("-- Do you wish to overwrite the directory? [Y/N]: ")
		if str[0].capitalize() == 'Y':
			rmtree("build")
			print("-- Removed build directory successfully")
		else:
			return 1
	os.mkdir("build")
	print("-- 'build' directory created successfully\n-- Running CMake...\n")
	if (os.system("cd build && cmake ..") == 0):
		print("\n-- CMake generated project files successfully")
		f = open("build/generate_project.py.output", 'w')
		f.write("This directory was generated by 'script/generate_project.py'")
		f.close()
		return 0
	else:
		print("-- FATAL: CMake failed to generate project files")
		return 1


def main_script():
	if (generate_project() == 0):
		input("Press enter to continue...")
	else:
		input("-- ABORTED: Press enter to continue...")
		exit(1)

if __name__ == "__main__":
	main_script()